version: '3.8'

services:
  mongo:
      image: mongo:latest
          container_name: mongo
              ports:
                    - "27017:27017"
                        environment:
                              MONGO_INITDB_ROOT_USERNAME: root
                                    MONGO_INITDB_ROOT_PASSWORD: example
                                        volumes:
                                              - mongo-data:/data/db

                                                redis:
                                                    image: redis:latest
                                                        container_name: redis
                                                            ports:
                                                                  - "6379:6379"
                                                                      volumes:
                                                                            - redis-data:/data

                                                                              server:
                                                                                  build: ./server
                                                                                      container_name: ronin-p2p-server
                                                                                          ports:
                                                                                                - "5000:5000"
                                                                                                    environment:
                                                                                                          INFURA_URL: https://saigon-testnet.roninchain.com/rpc
                                                                                                                ADMIN_WALLET: ${ADMIN_WALLET}
                                                                                                                      ADMIN_PRIVATE_KEY: ${ADMIN_PRIVATE_KEY}
                                                                                                                            MONGO_URI: mongodb://root:example@mongo:27017/
                                                                                                                                  REDIS_URL: redis://redis:6379
                                                                                                                                        CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
                                                                                                                                            depends_on:
                                                                                                                                                  - mongo
                                                                                                                                                        - redis

                                                                                                                                                          client:
                                                                                                                                                              build: ./client
                                                                                                                                                                  container_name: ronin-p2p-client
                                                                                                                                                                      ports:
                                                                                                                                                                            - "3000:3000"
                                                                                                                                                                                environment:
                                                                                                                                                                                      REACT_APP_API_URL: http://server:5000
                                                                                                                                                                                          depends_on:
                                                                                                                                                                                                - server

                                                                                                                                                                                                volumes:
                                                                                                                                                                                                  mongo-data:
                                                                                                                                                                                                    redis-data: