// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {RoninP2POffers} from "./RoninP2POffer.sol";
import {RoninP2pFeesAndPaymentsRoninP2PFeeAndRewardDistribution.sol";

contract RoninP2PTradeAgreement {
    struct Agreement {
            address creator;
                    address[] nfts;
                            uint256 modificationCount;
                                    bool isActive;
                                        }

                                            struct UserTransaction {
                                                    uint256 totalAmount;
                                                            uint256 transactionCount;
                                                                }

                                                                    mapping(uint256 => Agreement) public agreements;
                                                                        mapping(address => UserTransaction) public userTransactions;
                                                                            uint256 public agreementCounter;

                                                                                RoninP2POffer public roninP2POffer;
                                                                                    RoninP2PFeeAndRewardDistribution public roninP2PFeeAndRewardDistribution;

                                                                                        event AgreementCreated(uint256 agreementId, address creator);
                                                                                            event AgreementModified(uint256 agreementId, address modifiers);
                                                                                                event AgreementAccepted(uint256 agreementId, address accepter);
                                                                                                    event AgreementRejected(uint256 agreementId, address rejecter);
                                                                                                        event BatchTransfer(address[] recipients, uint256[] amounts);
                                                                                                            event UserTransactionLogged(address user, uint256 amount);

                                                                                                                constructor(address offerContract, address feeAndRewardContract) {
                                                                                                                        roninP2POffer = RoninP2POffer(offerContract);
                                                                                                                                roninP2PFeeAndRewardDistribution = RoninP2PFeeAndRewardDistribution(feeAndRewardContract);
                                                                                                                                    }

                                                                                                                                        function createTradeAgreement(address[] memory nfts) public {
                                                                                                                                                require(nfts.length <= 5, "Maximum 5 NFTs allowed");

                                                                                                                                                        Agreement memory newAgreement = Agreement({
                                                                                                                                                                    creator: msg.sender,
                                                                                                                                                                                nfts: nfts,
                                                                                                                                                                                            modificationCount: 0,
                                                                                                                                                                                                        isActive: true
                                                                                                                                                                                                                });

                                                                                                                                                                                                                        agreements[agreementCounter] = newAgreement;
                                                                                                                                                                                                                                emit AgreementCreated(agreementCounter, msg.sender);
                                                                                                                                                                                                                                        agreementCounter++;
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                function viewTradeAgreement(uint256 agreementId) public view returns (Agreement memory) {
                                                                                                                                                                                                                                                        return agreements[agreementId];
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                function modifyTradeAgreement(uint256 agreementId, address[] memory newNfts) public {
                                                                                                                                                                                                                                                                        Agreement storage agreement = agreements[agreementId];
                                                                                                                                                                                                                                                                                require(msg.sender == agreement.creator, "Only creator can modify");
                                                                                                                                                                                                                                                                                        require(agreement.modificationCount < 3, "Modification limit reached");
                                                                                                                                                                                                                                                                                                require(newNfts.length <= 5, "Maximum 5 NFTs allowed");

                                                                                                                                                                                                                                                                                                        agreement.nfts = newNfts;
                                                                                                                                                                                                                                                                                                                agreement.modificationCount++;
                                                                                                                                                                                                                                                                                                                        emit AgreementModified(agreementId, msg.sender);
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                function acceptTradeAgreement(uint256 agreementId, uint256 offerId) public {
                                                                                                                                                                                                                                                                                                                                        Agreement storage agreement = agreements[agreementId];
                                                                                                                                                                                                                                                                                                                                                require(agreement.isActive, "Agreement is not active");

                                                                                                                                                                                                                                                                                                                                                        RoninP2POffer.OfferDetails memory offer = roninP2POffer.viewOffer(offerId);
                                                                                                                                                                                                                                                                                                                                                                require(offer.agreementId == agreementId, "Invalid offer for this agreement");

                                                                                                                                                                                                                                                                                                                                                                        agreement.isActive = false;

                                                                                                                                                                                                                                                                                                                                                                                // Perform batch transfer of NFTs and tokens
                                                                                                                                                                                                                                                                                                                                                                                        address[] memory recipients = new address[](2);
                                                                                                                                                                                                                                                                                                                                                                                                recipients[0] = agreement.creator;
                                                                                                                                                                                                                                                                                                                                                                                                        recipients[1] = offer.offerer;

                                                                                                                                                                                                                                                                                                                                                                                                                uint256[] memory amounts = new uint256[](2);
                                                                                                                                                                                                                                                                                                                                                                                                                        amounts[0] = 1; // Placeholder for NFT transfer
                                                                                                                                                                                                                                                                                                                                                                                                                                amounts[1] = 1; // Placeholder for token transfer

                                                                                                                                                                                                                                                                                                                                                                                                                                        emit BatchTransfer(recipients, amounts);

                                                                                                                                                                                                                                                                                                                                                                                                                                                // Log user transactions
                                                                                                                                                                                                                                                                                                                                                                                                                                                        userTransactions[agreement.creator].totalAmount += amounts[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                userTransactions[agreement.creator].transactionCount += 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        userTransactions[offer.offerer].totalAmount += amounts[1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                userTransactions[offer.offerer].transactionCount += 1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        emit UserTransactionLogged(agreement.creator, amounts[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                emit UserTransactionLogged(offer.offerer, amounts[1]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        emit AgreementAccepted(agreementId, msg.sender);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function rejectTradeAgreement(uint256 agreementId) public {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Agreement storage agreement = agreements[agreementId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                require(agreement.isActive, "Agreement is not active");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        agreement.isActive = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                emit AgreementRejected(agreementId, msg.sender);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function viewUserTransactions(address user) public view returns (UserTransaction memory) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return userTransactions[user];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }