// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/IERC721.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import { RoninP2POffer } from "./RoninP2POffer.sol";
import { RoninP2PFeeAndRewardDistribution } from "./RoninP2PFeeAndRewardDistribution.sol";

contract RoninP2PTradeAgreement {
    struct Agreement {
            address creator;
                    address counterparty;
                            address[] nfts;
                                    address[] tokens;
                                            uint256[] tokenAmounts; // Added to specify amounts for each token
                                                    uint256 modificationCount;
                                                            bool isActive;
                                                                }

                                                                    struct UserTransaction {
                                                                            uint256 totalAmount;
                                                                                    uint256 transactionCount;
                                                                                        }

                                                                                            mapping(uint256 => Agreement) public agreements;
                                                                                                mapping(address => UserTransaction) public userTransactions;
                                                                                                    uint256 public agreementCounter;

                                                                                                        RoninP2POffer public roninP2POffer;
                                                                                                            RoninP2PFeeAndRewardDistribution public roninP2PFeeAndRewardDistribution;

                                                                                                                event AgreementCreated(uint256 agreementId, address creator);
                                                                                                                    event AgreementModified(uint256 agreementId, address counterparty); // Updated to use "counterparty"
                                                                                                                        event AgreementAccepted(uint256 agreementId, address accepter);
                                                                                                                            event AgreementRejected(uint256 agreementId, address rejecter);
                                                                                                                                event BatchTransfer(address[] recipients, uint256[] amounts);
                                                                                                                                    event UserTransactionLogged(address user, uint256 amount);

                                                                                                                                        constructor(address offerContract, address feeAndRewardContract) {
                                                                                                                                                roninP2POffer = RoninP2POffer(offerContract);
                                                                                                                                                        roninP2PFeeAndRewardDistribution = RoninP2PFeeAndRewardDistribution(feeAndRewardContract);
                                                                                                                                                            }

                                                                                                                                                                function createTradeAgreement(address[] memory nfts, address[] memory tokens, uint256[] memory tokenAmounts, address counterparty) public {
                                                                                                                                                                        require(nfts.length <= 5, "Maximum 5 NFTs allowed");
                                                                                                                                                                                require(tokens.length <= 5, "Maximum 5 tokens allowed");
                                                                                                                                                                                        require(tokens.length == tokenAmounts.length, "Tokens and tokenAmounts length mismatch");

                                                                                                                                                                                                Agreement memory newAgreement = Agreement({
                                                                                                                                                                                                            creator: msg.sender,
                                                                                                                                                                                                                        counterparty: counterparty,
                                                                                                                                                                                                                                    nfts: nfts,
                                                                                                                                                                                                                                                tokens: tokens,
                                                                                                                                                                                                                                                            tokenAmounts: tokenAmounts,
                                                                                                                                                                                                                                                                        modificationCount: 0,
                                                                                                                                                                                                                                                                                    isActive: true
                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                    agreements[agreementCounter] = newAgreement;
                                                                                                                                                                                                                                                                                                            emit AgreementCreated(agreementCounter, msg.sender);
                                                                                                                                                                                                                                                                                                                    agreementCounter++;
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                            function viewTradeAgreement(uint256 agreementId) public view returns (Agreement memory) {
                                                                                                                                                                                                                                                                                                                                    return agreements[agreementId];
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                            function modifyTradeAgreement(uint256 agreementId, address[] memory newNfts, address[] memory newTokens, uint256[] memory newTokenAmounts) public {
                                                                                                                                                                                                                                                                                                                                                    Agreement storage agreement = agreements[agreementId];
                                                                                                                                                                                                                                                                                                                                                            require(msg.sender == agreement.creator || msg.sender == agreement.counterparty, "Only creator or counterparty can modify");
                                                                                                                                                                                                                                                                                                                                                                    require(agreement.modificationCount < 3, "Modification limit reached");
                                                                                                                                                                                                                                                                                                                                                                            require(newNfts.length <= 5, "Maximum 5 NFTs allowed");
                                                                                                                                                                                                                                                                                                                                                                                    require(newTokens.length <= 5, "Maximum 5 tokens allowed");
                                                                                                                                                                                                                                                                                                                                                                                            require(newTokens.length == newTokenAmounts.length, "Tokens and tokenAmounts length mismatch");

                                                                                                                                                                                                                                                                                                                                                                                                    agreement.nfts = newNfts;
                                                                                                                                                                                                                                                                                                                                                                                                            agreement.tokens = newTokens;
                                                                                                                                                                                                                                                                                                                                                                                                                    agreement.tokenAmounts = newTokenAmounts;
                                                                                                                                                                                                                                                                                                                                                                                                                            agreement.modificationCount++;
                                                                                                                                                                                                                                                                                                                                                                                                                                    emit AgreementModified(agreementId, msg.sender); // Updated to use "msg.sender"
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                            function acceptTradeAgreement(uint256 agreementId, uint256 offerId) public {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    Agreement storage agreement = agreements[agreementId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                            require(agreement.isActive, "Agreement is not active");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    RoninP2POffer.OfferDetails memory offer = roninP2POffer.viewOffer(offerId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            require(offer.agreementId == agreementId, "Invalid offer for this agreement");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    agreement.isActive = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Perform batch transfer of NFTs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (uint256 i = 0; i < agreement.nfts.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                IERC721 nft = IERC721(agreement.nfts[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nft.safeTransferFrom(agreement.creator, offer.offerer, i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Perform batch transfer of tokens
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (uint256 i = 0; i < agreement.tokens.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                IERC20 token = IERC20(agreement.tokens[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            uint256 tokenAmount = agreement.tokenAmounts[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        token.transferFrom(offer.offerer, agreement.creator, tokenAmount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Log user transactions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (uint256 i = 0; i < agreement.tokens.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            uint256 tokenAmount = agreement.tokenAmounts[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        userTransactions[agreement.creator].totalAmount += tokenAmount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    userTransactions[agreement.creator].transactionCount += 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                userTransactions[offer.offerer].totalAmount += tokenAmount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            userTransactions[offer.offerer].transactionCount += 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            emit UserTransactionLogged(agreement.creator, 1 * 10**18); // Placeholder for token amount
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    emit UserTransactionLogged(offer.offerer, 1 * 10**18); // Placeholder for token amount

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            emit AgreementAccepted(agreementId, msg.sender);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function rejectTradeAgreement(uint256 agreementId) public {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Agreement storage agreement = agreements[agreementId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    require(agreement.isActive, "Agreement is not active");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            agreement.isActive = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    emit AgreementRejected(agreementId, msg.sender);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function viewUserTransactions(address user) public view returns (UserTransaction memory) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return userTransactions[user];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }